-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.sales_transaction
(
    customer bigint NOT NULL,
    date date,
    "time" time with time zone,
    sales_outlet "char" NOT NULL,
    staff "char" NOT NULL,
    transaction_id bigint NOT NULL,
    PRIMARY KEY (transaction_id)
);

CREATE TABLE public.sales_details
(
    details_id bigint NOT NULL,
    transaction_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity bigint NOT NULL,
    price real,
    PRIMARY KEY (details_id)
);

CREATE TABLE public.products
(
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    type_id bigint NOT NULL,
    description character varying(140) NOT NULL,
    price real,
    PRIMARY KEY (product_id)
);

CREATE TABLE public.products_type
(
    type_id bigint NOT NULL,
    type character varying(240),
    PRIMARY KEY (type_id)
);

CREATE TABLE public.products_category
(
    category_id bigint NOT NULL,
    category character varying(240),
    PRIMARY KEY (category_id)
);

ALTER TABLE public.sales_details
    ADD FOREIGN KEY (transaction_id)
    REFERENCES public.sales_transaction (transaction_id)
    NOT VALID;


ALTER TABLE public.sales_details
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (product_id)
    NOT VALID;


ALTER TABLE public.products
    ADD FOREIGN KEY (category_id)
    REFERENCES public.products_category (category_id)
    NOT VALID;


ALTER TABLE public.products
    ADD FOREIGN KEY (type_id)
    REFERENCES public.products_type (type_id)
    NOT VALID;

END;